export enum MongodbConstants {
    DATABASE_CONNECTION = 'DATABASE_CONNECTION',
    CARD_DESIGN_COLLECTION_NAME = 'Card-design',
    CARD_DESIGN_DOCUMENT = 'CARD_DESIGN_DOCUMENT',
    GAME_COLLECTION_NAME = 'Game',
    GAME_DOCUMENT = 'GAME_DOCUMENT',
    MATCH_COLLECTION_NAME = 'Match',
    MATCH_DOCUMENT = 'MATCH_DOCUMENT',
    PLAYER_COLLECTION_NAME = 'Player',
    PLAYER_DOCUMENT = 'PLAYER_DOCUMENT',
    USER_COLLECTION_NAME = 'User',
    USER_DOCUMENT = 'USER_DOCUMENT',
}