export enum MongodbConstants {
    DATABASE_CONNECTION = 'DATABASE_CONNECTION',
    GAME_COLLECTION_NAME = 'Game',
    GAME_DOCUMENT = 'GAME_DOCUMENT',
    PLAYER_COLLECTION_NAME = 'Player',
    PLAYER_DOCUMENT = 'PLAYER_DOCUMENT',
    USER_COLLECTION_NAME = 'User',
    USER_DOCUMENT = 'USER_DOCUMENT',
}